### ISSUE TITLE
[Question] Isaac vs RNGProvider?

### ISSUE THREAD

**Issue by firepacket** [nlebedenco/Carambolas#1]
Do you happen to have any evidence that Isaac RNG is better than the .NET built in cryptographic provider? Or does this class just not exist in the framework you are targeting?

Thanks.

**Comment by nlebedenco** [comment]
Ok, so what does "better" mean to you? Run faster? Less memory required? Larger period? Or do you mean better statistical properties? In this case which ones? Honestly I didn't run any deep analysis to pick ISAAC and I never considered it a top priority because secure connections represented only a fraction of the project. I wanted an RNG that was simple to implement and yet comparable to other cryptographically strong RNGs out there so I limited my research to what I could find comparative reports. I also wanted to steer away from System.Security.Cryptography.RNGCryptoServiceProvider for a few practical reasons: 
1. its underlying implementation may vary across platforms and .net flavors and I wanted to be able to compare Carambolas running in different platforms with as few deviations as possible;
2. I wanted to keep allocations at a minimum and there's no way to control internal allocations in RNGCryptoServiceProvider (if any);
3. I wanted to avoid the requirement to dispose the generator;
4. The interface provided by RNGCryptoServiceProvider was inconvenient. It can only fill up a pre-allocated byte array (or allocate one for you) and since I was interested in random numbers and random fixed size keys (not arbitrarily large byte sequences) I'd have to employ a wrapper of sorts anyway;

Note that the current ISSAC implementation in Carambolas is in fact a class with two internal byte arrays but this is again only for convenience so I could define a simple interface to experiment with other RNGs later on test beds. My original intention was to implement ISAAC as a mutable unsafe struct with two fixed size buffers for internal use only and thus have zero-allocations.
